import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-2">
          <a href="/api/auth/signout"
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-2 block w-fit"
          >
            Sign out
          </a>
          {children}
        </div>
      </body>
    </html>
  );
}